
// Tüm dosyaların yollarını içeren bir nesne

import file1 from '/download-files/الروح والجسد.pdf'
import file2 from '/download-files/من أسرار القرآن.pdf'
import file6 from '/download-files/العنكبوت.pdf'
import file10 from '/download-files/الأحلام.pdf'
import file5 from '/download-files/الماركسية والإسلام.pdf'
import file9 from '/download-files/الزعيم.pdf'
import file7 from '/download-files/حوار مع صديقي الملحد.pdf'
import file8 from '/download-files/رجل تحت الصفر.pdf'
import file3 from '/download-files/أينشتين والنسبية.pdf'
import file4 from '/download-files/يوميات نص الليل.pdf'
import file11 from '/download-files/الذين ضحكوا حتى البكاء.pdf'
import file12 from '/download-files/لغز الموت.pdf'
import file13 from '/download-files/أناشيد الإثم والبراءة.pdf'
import file14 from '/download-files/الإسلام ما هو؟.pdf'
import file15 from '/download-files/اعترافات عشاق.pdf'
import file16 from '/download-files/رأيت الله.pdf'
import file17 from '/download-files/على حافة الزلزال.pdf'
import file18 from '/download-files/مغامرة في الصحراء.pdf'
import file19 from '/download-files/إسرائيل البداية والنهاية.pdf'
import file20 from '/download-files/المؤامرة الكبرى.pdf'
import file21 from '/download-files/الله والإنسان.pdf'
import file22 from '/download-files/على حافة الانتحار.pdf'
import file23 from '/download-files/الوجود والعدم.pdf'
import file24 from '/download-files/الأفيون.pdf'
import file25 from '/download-files/الشيطان يسكن في بيتنا.pdf'
import file26 from '/download-files/الإسكندر الأكبر.pdf'
import file27 from '/download-files/الغد المشتعل.pdf'
import file28 from '/download-files/أكذوبة اليسار الإسلامي.pdf'
import file29 from '/download-files/إبليس.pdf'
import file30 from '/download-files/الشفاعة.pdf'
import file31 from '/download-files/عنبر .pdf'
import file32 from '/download-files/محمد .pdf'
import file33 from '/download-files/حقيقة البهائية.pdf'
import file34 from '/download-files/هل هو عصر الجنون ؟.pdf'
import file35 from '/download-files/جهنم الصغرى.pdf'
import file36 from '/download-files/تأملات في دنيا الله.pdf'
import file37 from '/download-files/الخروج من التابوت.pdf'
import file38 from '/download-files/الإسلام في خندق.pdf'
import file39 from '/download-files/رائحة الدم.pdf'
import file40 from '/download-files/الإنسان والظل.pdf'
import file41 from '/download-files/نقطة الغليان.pdf'
import file42 from '/download-files/ماذا وراء بوابة الموت.pdf'
import file43 from '/download-files/إسرائيل النازية ولغة المحرقة.pdf'
import file44 from '/download-files/زيارة للجنة والنار.pdf'
import file45 from '/download-files/الغابة.pdf'
import file46 from '/download-files/على خط النار.pdf'
import file47 from '/download-files/ألعاب السيرك السياسي.pdf'
import file48 from '/download-files/عظماء الدنيا وعظماء الآخرة.pdf'
import file49 from '/download-files/التوراة.pdf'
import file50 from '/download-files/الإسلام السياسي والمعركة القادمة.pdf'
import file51 from '/download-files/سقوط اليسار.pdf'
import file52 from '/download-files/55 مشكلة حب.pdf'
import file53 from '/download-files/الطريق إلى جهنم.pdf'
import file54 from '/download-files/الله.pdf'
import file55 from '/download-files/عصر القرود.pdf'
import file56 from '/download-files/من أمريكا إلى الشاطئ الآخر.pdf'
import file57 from '/download-files/كلمة السر.pdf'
import file58 from '/download-files/علم نفس قرآني جديد.pdf'
import file59 from '/download-files/شلة الأنس.pdf'
import file60 from '/download-files/السر الأعظم.pdf'
import file61 from '/download-files/القرآن محاولة لفهم عصري.pdf'
import file62 from '/download-files/لماذا رفضت الماركسية؟.pdf'
import file63 from '/download-files/قراءة للمستقبل.pdf'
import file64 from '/download-files/عالم الأسرار.pdf'
import file65 from '/download-files/حكايات مسافر.pdf'
import file66 from '/download-files/لغز الحياة.pdf'
import file67 from '/download-files/الطريق إلى الكعبة.pdf'
import file68 from '/download-files/الزلزال.pdf'
import file69 from '/download-files/سواح فى دنيا اله.pdf'
import file70 from '/download-files/أيها السادة اخلعوا الأقنعة.pdf'
import file71 from '/download-files/أكل عيش.pdf'
import file72 from '/download-files/المستحيل.pdf'
import file73 from '/download-files/رحلتي من الشك إلى الإيمان.pdf'
import file74 from '/download-files/الطوفان.pdf'
import file75 from '/download-files/في الحب والحياة.pdf'
import file76 from '/download-files/نار تحت الرماد.pdf'
import file77 from '/download-files/القرآن كائن حي.pdf'
import file78 from '/download-files/المسيخ الدجال.pdf'
import file79 from '/download-files/الشيطان يحكم.pdf'
import file80 from '/download-files/وبدأ العد التنازلي.pdf'
import file81 from '/download-files/السؤال الحائر.pdf'

const allFile = {

  file1,file2,file3,file4,file5,file6,file7,file8,file9,file10,file11,file12,file13,file14,file15,
  file16,file17,file18,file19,file20,file21,file22,file23,file24, file25, file26,file27,file28,
  file29,file30,file31,file32,file33,file34,file35,file36,file37, file38, file39,file40,file41,
  file42,file43,file44,file45,file46,file47,file48,file49,file50,file51,file52,file53,file54,file55,
  file56,file57,file58,file59,file60,file61,file62,file63,file64,file65,file66,file67,file68,
  file69,file70,file71,file72,file73,file74,file75,file76,file77,file78,file79,file80,file81
}


export default allFile