
import file1 from '../assets/download/الروح والجسد.pdf'
import file2 from '../assets/download/من أسرار القرآن.pdf'
import file6 from '../assets/download/العنكبوت.pdf'
import file10 from '../assets/download/الأحلام.pdf'
import file5 from '../assets/download/الماركسية والإسلام.pdf'
import file9 from '../assets/download/الزعيم.pdf'
import file7 from '../assets/download/حوار مع صديقي الملحد.pdf'
import file8 from '../assets/download/رجل تحت الصفر.pdf'
import file3 from '../assets/download/أينشتين والنسبية.pdf'
import file4 from '../assets/download/يوميات نص الليل.pdf'
import file11 from '../assets/download/الذين ضحكوا حتى البكاء.pdf'
import file12 from '../assets/download/لغز الموت.pdf'
import file13 from '../assets/download/أناشيد الإثم والبراءة.pdf'
import file14 from '../assets/download/الإسلام ما هو؟.pdf'
import file15 from '../assets/download/اعترافات عشاق.pdf'
import file16 from '../assets/download/رأيت الله.pdf'
import file17 from '../assets/download/على حافة الزلزال.pdf'
import file18 from '../assets/download/مغامرة في الصحراء.pdf'
import file19 from '../assets/download/إسرائيل البداية والنهاية.pdf'
import file20 from '../assets/download/المؤامرة الكبرى.pdf'
import file21 from '../assets/download/الله والإنسان.pdf'
import file22 from '../assets/download/على حافة الانتحار.pdf'
import file23 from '../assets/download/الوجود والعدم.pdf'
import file24 from '../assets/download/الأفيون.pdf'
import file25 from '../assets/download/الشيطان يسكن في بيتنا.pdf'
import file26 from '../assets/download/الإسكندر الأكبر.pdf'
import file27 from '../assets/download/الغد المشتعل.pdf'
import file28 from '../assets/download/أكذوبة اليسار الإسلامي.pdf'
import file29 from '../assets/download/إبليس.pdf'
import file30 from '../assets/download/الشفاعة.pdf'
import file31 from '../assets/download/عنبر .pdf'
import file32 from '../assets/download/محمد .pdf'
import file33 from '../assets/download/حقيقة البهائية.pdf'
import file34 from '../assets/download/هل هو عصر الجنون ؟.pdf'
import file35 from '../assets/download/جهنم الصغرى.pdf'
import file36 from '../assets/download/تأملات في دنيا الله.pdf'
import file37 from '../assets/download/الخروج من التابوت.pdf'
import file38 from '../assets/download/الإسلام في خندق.pdf'
import file39 from '../assets/download/رائحة الدم.pdf'
import file40 from '../assets/download/الإنسان والظل.pdf'
import file41 from '../assets/download/نقطة الغليان.pdf'
import file42 from '../assets/download/ماذا وراء بوابة الموت.pdf'
import file43 from '../assets/download/إسرائيل النازية ولغة المحرقة.pdf'
import file44 from '../assets/download/زيارة للجنة والنار.pdf'
import file45 from '../assets/download/الغابة.pdf'
import file46 from '../assets/download/على خط النار.pdf'
import file47 from '../assets/download/ألعاب السيرك السياسي.pdf'
import file48 from '../assets/download/عظماء الدنيا وعظماء الآخرة.pdf'
import file49 from '../assets/download/التوراة.pdf'
import file50 from '../assets/download/الإسلام السياسي والمعركة القادمة.pdf'
import file51 from '../assets/download/سقوط اليسار.pdf'
import file52 from '../assets/download/55 مشكلة حب.pdf'
import file53 from '../assets/download/الطريق إلى جهنم.pdf'
import file54 from '../assets/download/الله.pdf'
import file55 from '../assets/download/عصر القرود.pdf'
import file56 from '../assets/download/من أمريكا إلى الشاطئ الآخر.pdf'
import file57 from '../assets/download/كلمة السر.pdf'
import file58 from '../assets/download/علم نفس قرآني جديد.pdf'
import file59 from '../assets/download/شلة الأنس.pdf'
import file60 from '../assets/download/السر الأعظم.pdf'
import file61 from '../assets/download/القرآن محاولة لفهم عصري.pdf'
import file62 from '../assets/download/لماذا رفضت الماركسية؟.pdf'
import file63 from '../assets/download/قراءة للمستقبل.pdf'
import file64 from '../assets/download/عالم الأسرار.pdf'
import file65 from '../assets/download/حكايات مسافر.pdf'
import file66 from '../assets/download/لغز الحياة.pdf'
import file67 from '../assets/download/الطريق إلى الكعبة.pdf'
import file68 from '../assets/download/الزلزال.pdf'
import file69 from '../assets/download/سواح فى دنيا اله.pdf'
import file70 from '../assets/download/أيها السادة اخلعوا الأقنعة.pdf'
import file71 from '../assets/download/أكل عيش.pdf'
import file72 from '../assets/download/المستحيل.pdf'
import file73 from '../assets/download/رحلتي من الشك إلى الإيمان.pdf'
import file74 from '../assets/download/الطوفان.pdf'
import file75 from '../assets/download/في الحب والحياة.pdf'
import file76 from '../assets/download/نار تحت الرماد.pdf'
import file77 from '../assets/download/القرآن كائن حي.pdf'
import file78 from '../assets/download/المسيخ الدجال.pdf'
import file79 from '../assets/download/الشيطان يحكم.pdf'
import file80 from '../assets/download/وبدأ العد التنازلي.pdf'
import file81 from '../assets/download/السؤال الحائر.pdf'

const allFile = {

  file1,file2,file3,file4,file5,file6,file7,file8,file9,file10,file11,file12,file13,file14,file15,
  file16,file17,file18,file19,file20,file21,file22,file23,file24, file25, file26,file27,file28,
  file29,file30,file31,file32,file33,file34,file35,file36,file37, file38, file39,file40,file41,
  file42,file43,file44,file45,file46,file47,file48,file49,file50,file51,file52,file53,file54,file55,
  file56,file57,file58,file59,file60,file61,file62,file63,file64,file65,file66,file67,file68,
  file69,file70,file71,file72,file73,file74,file75,file76,file77,file78,file79,file80,file81
}


export default allFile